/**:
  ros__parameters:
    # Input Source Settings
    input:
      source: "zed_sdk"  # "ros2" 또는 "zed_sdk"
      zed:
        serial_number: 42384922
        resolution: "HD1080"  # HD2K, HD1080, HD720
        fps: 60
        depth_mode: "ULTRA"  # PERFORMANCE, QUALITY, ULTRA
        
    # Topic Settings (ROS2 source 사용시)
    topics:
      rgb_image: "/zed/zed_node/rgb/image_rect_color"
      depth_image: "/zed/zed_node/depth/depth_registered"
      camera_info: "/zed/zed_node/rgb/camera_info"
      feature_image: "feature_image"  # 발행할 토픽
      
    # Processing Parameters (연산 활성화 여부)
    processing:
      enable_feature_detection: true   # 특징점 검출 활성화
      enable_feature_matching: true    # 특징점 매칭 활성화
      enable_pose_estimation: true     # 포즈 추정 활성화
      publish_results: true            # 결과 토픽 발행 활성화

    # Feature Detector Parameters (연산 파라미터)
    feature_detector:
      max_features: 500
      scale_factor: 1.2
      n_levels: 8
      fast_threshold: 25
      image_scale: 0.2
      matching:
        ratio_threshold: 0.8
        cross_check: false

    # Visualization Parameters (시각화 설정)
    visualization:
      enable: true                    # 전체 시각화 활성화/비활성화
      window_width: 800
      window_height: 600
      window_pos_x: 100
      window_pos_y: 100
      windows:
        show_original: true           # 원본 이미지 윈도우
        show_features: true           # 특징점 윈도우
        show_matches: true            # 매칭 윈도우
      window_names:
        original: "Original Image"
        features: "Feature Detection"
        matches: "Feature Matches"

    # Image Processor Parameters
    image_processor:
      gaussian_blur_size: 0
      gaussian_sigma: 1.0
      enable_histogram_eq: false

    # Camera Parameters (기본값, 실제로는 카메라 info에서 업데이트됨)
    camera:
      fx: 525.0
      fy: 525.0
      cx: 319.5
      cy: 239.5
      width: 640
      height: 480

    # Visual Odometry Parameters
    vo:
      min_feature_distance: 30.0
      max_feature_distance: 5000.0
      min_matches: 10
      ransac_threshold: 3.0
      keyframe_rotation_threshold: 0.1  # radians
      keyframe_translation_threshold: 0.1  # meters 