/**:
  ros__parameters:
    # Input Source Settings
    input:
      source: "ros2"  # "ros2" 또는 "zed_sdk"
      zed:
        serial_number: 42384922
        resolution: "HD1080"  # HD2K, HD1080, HD720
        fps: 60
        depth_mode: "ULTRA"  # PERFORMANCE, QUALITY, ULTRA
        
    # Topic Settings (ROS2 source 사용시)
    topics:
      rgb_image: "/zed/zed_node/rgb/image_rect_color"
      depth_image: "/zed/zed_node/depth/depth_registered"
      camera_info: "/zed/zed_node/rgb/camera_info"
      feature_image: "feature_image"  # 발행할 토픽
      
    # Processing Parameters (연산 활성화 여부)
    processing:
      enable_feature_detection: true   # 특징점 검출 활성화
      enable_feature_matching: true    # 특징점 매칭 활성화
      enable_pose_estimation: false     # 포즈 추정 활성화
      publish_results: true            # 결과 토픽 발행 활성화

    # Feature Detector Parameters (연산 파라미터)
    feature_detector:
      max_features: 1000              # 최대 특징점 개수 "1000개 고정으로 수정 금지"
      scale_factor: 1.2             # 스케일 팩터
      n_levels: 8                   # 피라미드 레벨 수
      fast_threshold: 25            # FAST 임계값
      image_scale: 0.2              # 이미지 스케일
      min_distance: 15              # 특징점 간 최소 거리
      quality_level: 0.01           # 특징점 품질 레벨 (0.001-0.1)
      matching:
        ratio_threshold: 0.8        # 매칭 비율 임계값
        cross_check: false          # 교차 검사 사용 여부
        max_distance: 50            # 매칭점 간 최대 거리 (픽셀)
        min_matches: 10             # 최소 매칭 개수
        ransac:
          threshold: 3.0            # RANSAC 임계값 (픽셀)
          confidence: 0.99          # RANSAC 신뢰도 (0.9-0.99)
          max_iterations: 1000      # 최대 반복 횟수

    # Visualization Parameters (시각화 설정)
    visualization:
      enable: true                  # 전체 시각화 활성화/비활성화
      window_width: 800             # 윈도우 너비 (400-1920)
      window_height: 600            # 윈도우 높이 (300-1080)
      window_pos_x: 100             # 윈도우 X 위치 (0-1920)
      window_pos_y: 100             # 윈도우 Y 위치 (0-1080)
      fps_window_size: 60           # FPS 계산 윈도우 크기 (30-120)
      feature_size: 3               # 특징점 크기 (1-10)
      line_thickness: 2             # 선 두께 (1-5)
      windows:
        show_original: true         # 원본 이미지 윈도우
        show_features: true         # 특징점 윈도우
        show_matches: true          # 매칭 윈도우
      window_names:
        original: "Original Image"
        features: "Feature Detection"
        matches: "Feature Matches"

    # Image Processor Parameters
    image_processor:
      gaussian_blur_size: 0
      gaussian_sigma: 1.0
      enable_histogram_eq: false

    # Camera Parameters (기본값, 실제로는 카메라 info에서 업데이트됨)
    camera:
      fx: 525.0
      fy: 525.0
      cx: 319.5
      cy: 239.5
      width: 640
      height: 480

    # Visual Odometry Parameters
    vo:
      min_feature_distance: 30.0
      max_feature_distance: 5000.0
      min_matches: 10
      ransac_threshold: 3.0
      keyframe_rotation_threshold: 0.1  # radians
      keyframe_translation_threshold: 0.1  # meters 